<?php

namespace AppBundle\Repository;

/**
 * QcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
